"use client";
import {useState} from "react";

type Result=any;
export default function Home(){
 const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [type,setType]=useState("code"); const [result,setResult]=useState<Result>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function run(){setLoading(true);setError("");setResult(null);try{const r=await fetch("/api/commercialize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,type})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");setResult(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <main className="shell"><nav className="nav"><div className="brand">IP CODE EXCHANGE</div><div className="tag">4.2.0 • commercialization engine</div></nav>
 <section className="hero"><h1>Turn dormant IP into commercial opportunities.</h1><p>Analyze an asset, estimate commercial value, identify buyer categories, choose licensing paths, and generate first-contact outreach from one workflow.</p></section>
 <section className="grid"><div className="card"><h2>Commercialize an asset</h2><label className="label">Asset name</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Autonomous Agent Framework"/><label className="label">Asset type</label><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>code</option><option>prototype</option><option>dataset</option><option>document</option></select><label className="label">Describe the IP</label><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does it do? What is technically distinctive? Who might use it?"/><div className="actions"><button className="button" disabled={loading||!name||!description} onClick={run}>{loading?"Running engine…":"Run commercialization analysis"}</button></div>{error&&<p className="small">{error}</p>}</div>
 <div className="card"><h2>Pipeline</h2><p className="muted">One asset enters. A commercialization brief comes out.</p><div><span className="pill">Asset analysis</span><span className="pill">Valuation</span><span className="pill">Buyer discovery</span><span className="pill">Licensing</span><span className="pill">Outreach</span></div>{result&&<div className="result"><div className="metric">${Number(result.valuation||0).toLocaleString()}</div><div className="muted">screening valuation estimate</div><p>{result.summary}</p><h3>Commercial components</h3><ul>{(result.monetizableComponents||[]).map((x:string)=><li key={x}>{x}</li>)}</ul><h3>Licensing paths</h3><ul>{(result.licensingPaths||[]).map((x:string)=><li key={x}>{x}</li>)}</ul><h3>Buyer targets</h3>{(result.buyers||[]).map((b:any)=><div className="buyer" key={b.name}><span className="score">{Math.round((b.fitScore||0)*100)}%</span><strong>{b.name}</strong><div className="muted">{b.segment}</div><div className="small">{b.reason}</div></div>)}<h3>Outreach</h3>{(result.outreach||[]).map((m:any,i:number)=><div className="buyer" key={i}><strong>{m.subject}</strong><div className="small">{m.body}</div></div>)}</div>}</div></section>
 <div className="footer">This product provides AI-assisted commercial screening, not legal, accounting, patent, or investment advice. Buyer discovery is a starting point for human verification.</div></main>
}
